name: Publish Releases

on:
  release:
    types: [released]

jobs:
  Release-FireFox:
    runs-on: ubuntu-latest
    outputs:
      filename: ${{ steps.build.outputs.filename }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4.0.2
      with:
        node-version: '18.x'
    - name: Install dependencies
      run: npm install
    - name: build firefox
      run: npm run build
    - name: zip firefox
      id: build
      run: |
        make firefox
        echo "filename=blue-blocker-firefox-$(make version).zip" >> "$GITHUB_OUTPUT"
    - name: publish firefox
      uses: wdzeng/firefox-addon@v1.0.5
      with:
        addon-guid: "{119be3f3-597c-4f6a-9caf-627ee431d374}"
        xpi-path: "${{ steps.build.outputs.filename }}"
        self-hosted: false
        release-notes: "{\"en-US\": toJSON(${{ github.event.body }})}" # this should be the content of the release, make sure to include changelog
        approval-notes: "source code for this version is available at https://github.com/kheina-com/Blue-Blocker/releases/tag/${{ github.event.tag_name }}\nrunning `npm run build` and then `make firefox` should build the addon package, then load and use twitter. you should start seeing users be blocked fairly quickly"
        license: MPL-2.0
        jwt-issuer: ${{ secrets.MOZILLA_ADDONS_JWT_ISSUER }}
        jwt-secret: ${{ secrets.MOZILLA_ADDONS_JWT_SECRET }}

  Release-Chrome:
    runs-on: ubuntu-latest
    outputs:
      filename: ${{ steps.build.outputs.filename }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4.0.2
      with:
        node-version: '18.x'
    - name: Install dependencies
      run: npm install
    - name: build chrome
      run: npm run build
    - name: zip chrome
      id: build
      run: |
        make chrome
        echo "filename=blue-blocker-chrome-$(make version).zip" >> "$GITHUB_OUTPUT"
    - name: publish chrome
      uses: mnao305/chrome-extension-upload@v5.0.0
      with:
        refresh-token: ${{ secrets.CHROME_WEB_STORE_REFRESH_TOKEN }}
        client-id: ${{ secrets.CHROME_WEB_STORE_CLIENT_ID }}
        client-secret: ${{ secrets.CHROME_WEB_STORE_CLIENT_SECRET }}
        file-path: "${{ steps.build.outputs.filename }}"
        extension-id: "jgpjphkbfjhlbajmmcoknjjppoamhpmm"
        publish: true
